### PR TITLE
Miscellaneous test fixes

### PR DESCRIPTION
**Pull request by kyleam**
This series resolves three test failures that occur on the latest Metworx under R 4.3.

The large number of changed files is coming from the deletion of `cmd/load_test.go` and associated files.

```
$ git diff --name-only af56210c9^-1 | wc -l
    3350

$ git diff --name-only af56210c9^-1 | cut -d/ -f1-4 | sort | uniq -c
   1 cmd/load_test.go
1716 cmd/testsite/golden/load
1633 cmd/testsite/golden/load-fail

$ git diff --name-only af56210c9..5401687
integration_tests/baseline/install_test.go
integration_tests/mixed-source/.gitignore
integration_tests/mixed-source/mixed_source_test.go
integration_tests/mixed-source/pkgr-linux.yml.template
integration_tests/mixed-source/setup-binary-repo.sh
localrepos/bad-xml2/src/contrib/PACKAGES
localrepos/bad-xml2/src/contrib/PACKAGES.gz
localrepos/bad-xml2/src/contrib/PACKAGES.rds
localrepos/bad-xml2/src/contrib/RCurl_1.95-4.12.tar.gz
localrepos/bad-xml2/src/contrib/RCurl_1.98-1.16.tar.gz
```

diff excluding first commit: https://github.com/metrumresearchgroup/pkgr/compare/af56210c983fb34ebdfb9b5313591afa13d7bc93...540168759fbf5af5b66840644c10c560308954a3

### CODE REVIEW

**Comment by kyleam** [comment]
Drone runs:
* https://github-drone.metrumrg.com/metrumresearchgroup/pkgr/273
* https://github-drone.metrumrg.com/metrumresearchgroup/pkgr/274

**Comment by kyleam** [comment]
Metworx results for tests of packages touched by this series:

```
$ ./t.sh
ok  	github.com/metrumresearchgroup/pkgr/cmd	119.169s
ok  	github.com/metrumresearchgroup/pkgr/integration_tests/mixed-source	20.395s
ok  	github.com/metrumresearchgroup/pkgr/integration_tests/baseline	248.520s
```

<details>
<summary>test script</summary>

```sh
#!/bin/sh

set -eu

tdir=$(mktemp -d "${TMPDIR:-/tmp}"/pkgr-test-XXXXX)
trap 'rm -rf "$tdir"' 0

cache=$tdir/cache
mkdir "$cache"
# Prevent tests from touching user's real cache.
export XDG_CACHE_HOME="$cache"

go test -count 1 ./cmd

bin=$tdir/bin
mkdir "$bin"

go build -o "$bin/pkgr" cmd/pkgr/pkgr.go

export PATH="$bin:$PATH"

cd integration_tests/mixed-source
go test -count 1 ./...
cd ../../integration_tests/baseline
go test -count 1 ./...
```

</details>

**Review by seth127 — APPROVED** [review]
This all makes sense to me. Thanks for documenting the changes and rationale in the commit messages. That made this much easier to review, especially since so many (mostly incidental) files changed. I also ran the test script you included and see the same passing results.

One comment for posterity: in the commit message for af56210c983fb34ebdfb9b5313591afa13d7bc93 you say

> These cases are already covered by the load integration test, so
remove the load tests under cmd.

I agree with that rationale. When I use the machinery on the `valtools` branch (in #419), which includes these changes, I can see that the test coverage for `cmd/load.go` is still above 90%, even with these tests removed.

```
$ make vt-all
$ cat internal/valtools/output/pkgr_3.1.1-46-g35eb4df/pkgr_3.1.1-46-g35eb4df.coverage.json
...
    {
      "file": "cmd/load.go",
      "coverage": 90.9090909090909
    }
...
```

**Comment by kyleam** [comment]
> When I use the machinery on the `valtools` branch (in #419), which includes these changes, I can see that the test coverage for `cmd/load.go` is still above 90%, even with these tests removed

Thanks for adding that.

**Pull request merged**
