### PR TITLE
Update command package

### PR DESCRIPTION
**Pull request by elisarver**
This follows #387 and updates the tests to use the new library format.

### CODE REVIEW

**Comment by dpastoor** [comment]
Cool deal! I can take a look tomorrow afternoon

**Review by dpastoor — APPROVED** [review]
LGTM - does make me slightly wonder about the whole "should we return bytes or just ack that most people want a string". Still feels right to do bytes.

Failing test is expected to still be failing

**Comment by elisarver** [comment]
> LGTM - does make me slightly wonder about the whole "should we return bytes or just ack that most people want a string". Still feels right to do bytes.

There's a pretty strong reason the standard lib is all-in on `[]byte` rather than strings: `[]byte` are mutable, and addressable by cell. And `string` are immutable. Lots of allocation when you handle strings.

**Comment by elisarver** [comment]
I'm pretty confident in my results here, since it's a simple transform. Merging.

**Pull request merged**
