### PR TITLE
add: update command for plan.

### PR DESCRIPTION
**Pull request by Dreznel**

### CODE REVIEW

**Comment by Dreznel** [comment]
addresses #77 and #74

**Comment by Dreznel** [comment]
I'm not strongly opinionated on this, but I personally prefer the word update. I would argue in favor of keeping it as update so that it matches thematically with update.packages.

As for number 2, I'm get on that.

And thanks! I agree, I tried really hard to be onboard with Go's naming conventions, but at least for pkgr, I'm finding it much easier to navigate after giving up those conventions.

**Comment by Dreznel** [comment]
@dpastoor merge is done, there weren't any real conflicts.

**Comment by Dreznel** [comment]
To validate:

#74
- [ ]  update flag can be set in config or passed in as an argument (--update)
- [ ] update argument overrides config
- [ ] running `pkgr plan --update` (or the equivalent using the config) will list the packages that will be updated, as well as what version they are currently on and what they will update to.
- [ ] running `pkgr plan` without the update setting will warn you about outdated packages

#61 
- [ ] for `pkgr install`, package name and version number are logged at an info level for prior-installed packages. 
- [ ] For `pkgr plan`, this information is logged at a debug level (to avoid verbosity)

#69 
- [ ] `pkgr install --update` (or the equivalent using the config file) installs all outdated packages specified to the latest available version in the specified repo.
- [x] Install with update does not currently check all available repos for most recent version -- it will use the first repo it finds. This is unideal but not in scope for this issue.
- [ ] If update operation fails, pkgr reinstates the previously-installed version.
- [x] If update operation is interrupted via a user command of some kind, we do not expect pkgr to be able to clean itself up.
- [ ] If nothing is specified in arguments or config, pkgr does not update.

#62 
- [ ] `pkgr install --loglevel debug` lists the size of package downloads in Megabytes.

#75 
- [ ] Package repositories to use are logged at an Info level for user-packages and a Debug level for dependencies.
- [ ] `pkgr plan/install` logs a brief "installation status" report detailing how many packages are required, how many are installed already, how many are outdated, and how many are to be installed or updated.

**Comment by dpastoor** [comment]
attempting #74 looks really close, however noticed an artifact:

get a negative number of the number of packages to install, when no new packages need to be installed

image

**Comment by Dreznel** [comment]
Started looking into the negative package numbers thing -- I think the issue is specifically when one removes packages from their config and then re-runs pkgr plan after already having installed.

I'll look into a fix for this.

**Comment by dpastoor** [comment]
@Dreznel I think I know the root cause - namely if there are packages that have been installed to that folder from other entities than pkgr then the number of total packages can exceed that which would be installed/managed by pkgr. 

Hence, its not really a bug, but actually an unexpected feature.

**Comment by dpastoor** [comment]
LGTM!

**Pull request merged**
